language: python
os: linux
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
jobs:
  include:
    - python: '3.6'
      env:
        - TOXENV=check
    - python: '3.6'
      env:
        - TOXENV=docs
    - env:
        - TOXENV=py35-cover,codecov
      python: '3.5'
    - env:
        - TOXENV=py35-nocov
      python: '3.5'
    - env:
        - TOXENV=py36-cover,codecov
      python: '3.6'
    - env:
        - TOXENV=py36-nocov
      python: '3.6'
    - env:
        - TOXENV=py37-cover,codecov
      python: '3.7'
    - env:
        - TOXENV=py37-nocov
      python: '3.7'
    - os: osx
      language: generic
      env:
        - TOXENV=py37-nocov
    - os: windows
      language: shell
      env:
        - TOXENV=py37-nocov
        - LD_PRELOAD=
    - env:
        - TOXENV=py38-cover,codecov
      python: '3.8'
    - env:
        - TOXENV=py38-nocov
      python: '3.8'
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - |
    if [[ $TRAVIS_OS_NAME == 'windows' ]]; then
        choco install python --params /quiet /InstallDir:C:\\python3 /Include_doc 0 /PrependPath 1
        python --version
        python -m pip install pyenv-win --target /c/pyenv
        python3 --version
        python3 -m pip install pyenv-win --target /c/pyenv
        find / -name pip
        find / -name pip3
        pip3 install pyenv-win --target /c/pyenv
    fi
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]] || [[ $TRAVIS_OS_NAME == 'windows' ]]; then
      python --version
      which python
      eval "$(pyenv init -)"
      pyenv rehash
      pyenv install 3.7-dev
      pyenv global 3.7-dev
      python --version
      which python
    fi
install:
  - python -mpip install --progress-bar=off tox -r ci/requirements.txt
  - easy_install --version
  - whereis virtualenv || true
  - which virtualenv
  - virtualenv --version
  - pip --version
  - tox --version
script:
    - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
