language: python

cache: pip

matrix:
    include:
        - os: linux
          python: "3.3"
        - os: linux
          python: "3.6"
        - os: linux
          python: "nightly"
        - os: osx
          language: generic

install: pip install tox

script: tox

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc
