language: python
dist: xenial
cache: false
env:
  global:
      if os == linux:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=check
    - python: '3.6'
      env:
        - TOXENV=docs
{%- for env, config in tox_environments|dictsort %}{{ '' }}
    - env:
        - TOXENV={{ env }}{% if config.cover %},codecov{% endif %}
{%- if env.startswith('pypy3') %}{{ '' }}
       - TOXPYTHON=pypy3
      python: 'pypy3'
{%- elif env.startswith('pypy') %}{{ '' }}
      python: 'pypy'
{%- else %}{{ '' }}
      python: '{{ "{0[2]}.{0[3]}".format(env) }}'
{%- endif %}
{%- if env in  ['py37-nocov'] %}{{ '' }}
    - os: osx
      language: generic
      env:
        - TOXENV={{ env }}
    - os: windows
      language: generic
      env:
        - TOXENV={{ env }}
        - LD_PRELOAD=
{%- endif %}{{ '' }}
{%- endfor %}{{ '' }}
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - |
      if os = windows:
        choco install python3 --params '/InstallDir:C:\python3'
        set PATH='\%PATH\%;c:\python3'
        echo 'Installed python base in \%PATH\%'
        pip install pyenv-win --target c:\pyenv
        set PATH="c:\pyenv\pyenv-win\bin:c:\pyenv\pyenv-win\shims:\PATH\%"
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]] || [[ $TRAVIS_OS_NAME == 'windows' ]]; then
      python --version
      which python
      eval "$(pyenv init -)"
      pyenv rehash
      pyenv install 3.7-dev
      pyenv global 3.7-dev
      python --version
      which python
    fi
install:
  - python -mpip install --progress-bar=off tox -r ci/requirements.txt
  - easy_install --version
  - whereis virtualenv || true
  - which virtualenv
  - virtualenv --version
  - pip --version
  - tox --version
script:
    - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
